In [1]:
import json
from pathlib import Path

import pandas as pd
import biopsykit as bp
from fau_colors import cmaps, register_fausans_font

import matplotlib.pyplot as plt
import seaborn as sns

from empkins_io.datasets.d03.micro_gapvii import MicroBaseDataset, MicroEcgDataset

%load_ext autoreload
%autoreload 2
%matplotlib widget

In [2]:
register_fausans_font()
plt.close("all")

palette = sns.color_palette(cmaps.faculties)
sns.set_theme(context="notebook", style="ticks", font="sans-serif", palette=palette)

plt.rcParams["figure.figsize"] = (10, 5)
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["mathtext.default"] = "regular"

palette

[(0.0, 0.1843137254901961, 0.4235294117647059),
 (0.4666666666666667, 0.6235294117647059, 0.7098039215686275),
 (1.0, 0.7215686274509804, 0.10980392156862745),
 (0.0, 0.6392156862745098, 0.8784313725490196),
 (0.2627450980392157, 0.6901960784313725, 0.16470588235294117),
 (0.7843137254901961, 0.06274509803921569, 0.1803921568627451)]

In [3]:
deploy_type = "local"

config_dict = json.load(Path("../config.json").open(encoding="utf-8"))

base_path = Path(config_dict[deploy_type]["base_path"])
base_path

PosixPath('/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro')

In [4]:
dataset = MicroEcgDataset(base_path, phase_fine=False, exclude_missing_data=False, use_cache=True)
dataset

MicroEcgDataset [1060 groups/rows]

        subject condition     phase
   0     VP_001      tsst  Baseline
   1     VP_001      tsst      Prep
   2     VP_001      tsst      Talk
   3     VP_001      tsst      Math
   4     VP_001      tsst  Recovery
   ...      ...       ...       ...
   1055  VP_110     ftsst  Baseline
   1056  VP_110     ftsst      Prep
   1057  VP_110     ftsst      Talk
   1058  VP_110     ftsst      Math
   1059  VP_110     ftsst  Recovery

   [1060 rows x 3 columns]

In [14]:
dataset_test = MicroBaseDataset(base_path, phase_fine=False, exclude_missing_data=False, use_cache=False)
dataset_test._get_nilspod_data("VP_014", "ftsst", None)

/Users/abelluc/Code/empkins-d03-preprocessing/.venv/lib/python3.9/site-packages/nilspodlib/session.py:458: SynchronisationWarning: For the sensors with the ids ['b0c2'] the last syncpackage occurred more than 30 s before the end of the dataset. The last section of this data should not be trusted.
  warnings.warn(

                                       157e                                \
                                      gyr_x     gyr_y     gyr_z     acc_x
time
2023-02-27 15:21:24.039062+01:00   0.854492  0.610352  0.122070 -0.455054
2023-02-27 15:21:24.042968+01:00   0.915527  0.610352  0.061035 -0.445474
2023-02-27 15:21:24.046875+01:00   0.915527  0.610352  0.000000 -0.469424
2023-02-27 15:21:24.050781+01:00   0.732422  0.610352  0.000000 -0.464634
2023-02-27 15:21:24.054687+01:00   0.488281  0.427246  0.061035 -0.455054
...                                     ...       ...       ...       ...
2023-02-27 15:54:11.554687+01:00 -19.470215  7.019043  8.728027 -2.605781
2023-02-27 15:54:11.558593+01:00 -19.592285  6.835938  8.666992 -2.562671
2023-02-27 15:54:11.562500+01:00 -19.531250  7.202148  8.666992 -2.505190
2023-02-27 15:54:11.566406+01:00 -19.226074  8.056641  8.850098 -2.438130
2023-02-27 15:54:11.570312+01:00 -18.981934  9.460449  9.033203 -2.361489

                                                          3d73            \
                                     acc_y     acc_z     gyr_x     gyr_y
time
2023-02-27 15:21:24.039062+01:00 -9.771680  1.571133  0.122070  0.854492
2023-02-27 15:21:24.042968+01:00 -9.771680  1.590293  0.061035  0.976562
2023-02-27 15:21:24.046875+01:00 -9.805210  1.604663  0.000000  0.854492
2023-02-27 15:21:24.050781+01:00 -9.776470  1.595083 -0.122070  0.854492
2023-02-27 15:21:24.054687+01:00 -9.718989  1.580713 -0.122070  0.854492
...                                    ...       ...       ...       ...
2023-02-27 15:54:11.554687+01:00 -6.696475 -7.165898  0.000000  0.732422
2023-02-27 15:54:11.558593+01:00 -6.725215 -7.185059  0.000000  0.732422
2023-02-27 15:54:11.562500+01:00 -6.739585 -7.127578  0.000000  0.793457
2023-02-27 15:54:11.566406+01:00 -6.739585 -7.079678  0.061035  0.732422
2023-02-27 15:54:11.570312+01:00 -6.753955 -7.074888 -0.061035  0.732422

                                                      ...     9e02           \
                                     gyr_z     acc_x  ... analog_0 analog_1
time                                                  ...
2023-02-27 15:21:24.039062+01:00 -0.061035 -0.023950  ...    159.0    167.0
2023-02-27 15:21:24.042968+01:00 -0.061035 -0.014370  ...    255.0    167.0
2023-02-27 15:21:24.046875+01:00  0.000000 -0.028740  ...    223.0    168.0
2023-02-27 15:21:24.050781+01:00 -0.061035 -0.038320  ...    129.0    167.0
2023-02-27 15:21:24.054687+01:00 -0.061035 -0.038320  ...     66.0    167.0
...                                    ...       ...  ...      ...      ...
2023-02-27 15:54:11.554687+01:00  0.122070 -0.210762  ...    187.0     10.0
2023-02-27 15:54:11.558593+01:00  0.061035 -0.225132  ...     81.0      8.0
2023-02-27 15:54:11.562500+01:00  0.000000 -0.244292  ...     89.0      9.0
2023-02-27 15:54:11.566406+01:00  0.061035 -0.244292  ...    184.0      8.0
2023-02-27 15:54:11.570312+01:00  0.000000 -0.244292  ...    255.0      7.0

                                                b0c2                       \
                                 analog_2      gyr_x     gyr_y      gyr_z
time
2023-02-27 15:21:24.039062+01:00    174.0  -0.732422 -0.061035   0.000000
2023-02-27 15:21:24.042968+01:00    251.0  -0.793457 -0.122070   0.000000
2023-02-27 15:21:24.046875+01:00    191.0  -0.793457 -0.305176   0.000000
2023-02-27 15:21:24.050781+01:00     36.0  -0.793457 -0.305176   0.000000
2023-02-27 15:21:24.054687+01:00     43.0  -0.732422 -0.366211  -0.061035
...                                   ...        ...       ...        ...
2023-02-27 15:54:11.554687+01:00     53.0 -15.258789  4.272461  11.840820
2023-02-27 15:54:11.558593+01:00      0.0 -15.014648  5.310059  12.084961
2023-02-27 15:54:11.562500+01:00     18.0 -14.953613  5.859375  12.145996
2023-02-27 15:54:11.566406+01:00    132.0 -14.953613  6.591797  12.207031
2023-02-27 15:54:11.570312+01:00    196.0 -14.953613  6.774902  12.207031


                                     acc_x     acc_y     acc_z     ecg
time
2023-02-27 15:21:24.039062+01:00  0.124541 -9.757310 -2.016606     4.0
2023-02-27 15:21:24.042968+01:00  0.129331 -9.762100 -2.016606    -4.0
2023-02-27 15:21:24.046875+01:00  0.138911 -9.776470 -2.011816   -37.0
2023-02-27 15:21:24.050781+01:00  0.138911 -9.781260 -2.007026   -53.0
2023-02-27 15:21:24.054687+01:00  0.134121 -9.776470 -2.002236   -90.0
...                                    ...       ...       ...     ...
2023-02-27 15:54:11.554687+01:00 -3.472778 -6.083350 -6.730005 -1317.0
2023-02-27 15:54:11.558593+01:00 -3.458408 -6.078560 -6.648574  -616.0
2023-02-27 15:54:11.562500+01:00 -3.458408 -6.083350 -6.610254  -237.0
2023-02-27 15:54:11.566406+01:00 -3.472778 -6.073770 -6.547983  -132.0
2023-02-27 15:54:11.570312+01:00 -3.487148 -6.064189 -6.528823  -140.0

[503689 rows x 28 columns]

In [16]:
hr_results_all = pd.DataFrame()
error_dict = {}

In [18]:
for subset in dataset.groupby(["subject", "condition", "phase"]):
    
    participant = subset.index["subject"].iloc[0]
    condition = subset.index["condition"].iloc[0]
    phase = subset.index["phase"].iloc[0]

    # check if phase is pause
    if "Pause" in phase.split("_"):
        continue

    # before baseline and recovery bug fix
    #if participant not in ["VP_001", "VP_002", "VP_003", "VP_004", "VP_005", "VP_006", "VP_007", "VP_008", "VP_009", "VP_010", "VP_019", "VP_021", "VP_022", "VP_025", "VP_026", "VP_027", "VP_031", "VP_032", "VP_033", "VP_034", "VP_036", "VP_037", "VP_041", "VP_044", "VP_045", "VP_050", "VP_051", "VP_052", "VP_053", "VP_054", "VP_059", "VP_060", "VP_061", "VP_062", "VP_063", "VP_065", "VP_066", "VP_067", "VP_082", "VP_083", "VP_096", "VP_101", "VP_102", "VP_103", "VP_110"]:
    #    continue

    #if participant in ["VP_001", "VP_002", "VP_003", "VP_004", "VP_005", "VP_006", "VP_007", "VP_008", "VP_009", "VP_010"]:
    #    continue

    if hr_results_all.index.isin([(participant, condition, phase)]).any():
        continue

    print(participant, condition, phase)

    try:

        data = subset.ecg
        
        ep = bp.signals.ecg.EcgProcessor(data={"Data": data}, sampling_rate=256)
        ep.ecg_process(errors="warn")

        hr_results = ep.hrv_process(ep, "Data", index=participant, index_name="participant")
        
        hr_results["HR_Mean"] = ep.hr_result["Data"].mean()[0]
        hr_results["HR_SD"] = ep.hr_result["Data"].std()[0]
        hr_results.index = pd.MultiIndex.from_arrays([[participant], [condition], [phase]], names=("participant", "condition", "phase"))
        
        hr_results_all = pd.concat((hr_results_all, hr_results))
    except Exception as e:
        if (participant, condition) not in error_dict:
            error_dict[(participant, condition)] = e

VP_001 tsst Baseline
VP_001 tsst Prep
VP_001 tsst Talk
VP_001 tsst Math
VP_001 tsst Recovery
VP_001 ftsst Baseline
VP_001 ftsst Prep
VP_001 ftsst Talk
VP_001 ftsst Math
VP_001 ftsst Recovery
VP_002 tsst Baseline
VP_002 tsst Prep
VP_002 tsst Talk
VP_002 tsst Math
VP_002 tsst Recovery
VP_002 ftsst Baseline
VP_002 ftsst Prep
VP_002 ftsst Talk
VP_002 ftsst Math
VP_002 ftsst Recovery
VP_003 tsst Baseline
VP_003 tsst Prep
VP_003 tsst Talk
VP_003 tsst Math
VP_003 tsst Recovery
VP_003 ftsst Baseline
VP_003 ftsst Prep
VP_003 ftsst Talk
VP_003 ftsst Math
VP_003 ftsst Recovery
VP_004 tsst Baseline
VP_004 tsst Prep
VP_004 tsst Talk
VP_004 tsst Math
VP_004 tsst Recovery
VP_004 ftsst Baseline
VP_004 ftsst Prep
VP_004 ftsst Talk
VP_004 ftsst Math
VP_004 ftsst Recovery
VP_005 tsst Baseline
VP_005 tsst Prep
VP_005 tsst Talk
VP_005 tsst Math
VP_005 tsst Recovery
VP_005 ftsst Baseline
VP_005 ftsst Prep
VP_005 ftsst Talk
VP_005 ftsst Math
VP_005 ftsst Recovery
VP_006 tsst Baseline
VP_006 tsst Prep
VP_006 tsst Talk
VP_006 tsst Math
VP_006 tsst Recovery
VP_006 ftsst Baseline
VP_006 ftsst Prep
VP_006 ftsst Talk
VP_006 ftsst Math
VP_006 ftsst Recovery
VP_007 tsst Baseline
VP_007 tsst Prep
VP_007 tsst Talk
VP_007 tsst Math
VP_007 tsst Recovery
VP_007 ftsst Baseline
VP_007 ftsst Prep
VP_007 ftsst Talk
VP_007 ftsst Math
VP_007 ftsst Recovery
VP_008 tsst Baseline
VP_008 tsst Prep
VP_008 tsst Talk
VP_008 tsst Math
VP_008 tsst Recovery
VP_008 ftsst Baseline
VP_008 ftsst Prep
VP_008 ftsst Talk
VP_008 ftsst Math
VP_008 ftsst Recovery
VP_009 tsst Baseline
VP_009 tsst Prep
VP_009 tsst Talk
VP_009 tsst Math
VP_009 tsst Recovery
VP_010 tsst Baseline
VP_010 tsst Prep
VP_010 tsst Talk
VP_010 tsst Math
VP_010 tsst Recovery
VP_014 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_019 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_019 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_019 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_019 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_019 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_021 tsst Baseline
VP_021 tsst Prep
VP_021 tsst Talk
VP_021 tsst Math
VP_021 tsst Recovery
VP_022 tsst Baseline
VP_022 tsst Prep
VP_022 tsst Talk
VP_022 tsst Math
VP_022 tsst Recovery
VP_022 ftsst Baseline
VP_022 ftsst Prep
VP_022 ftsst Talk
VP_022 ftsst Math
VP_022 ftsst Recovery
VP_025 tsst Baseline
VP_025 tsst Prep
VP_025 tsst Talk
VP_025 tsst Math
VP_025 tsst Recovery
VP_025 ftsst Baseline
VP_025 ftsst Prep
VP_025 ftsst Talk
VP_025 ftsst Math
VP_025 ftsst Recovery
VP_026 tsst Baseline
VP_026 tsst Prep
VP_026 tsst Talk
VP_026 tsst Math
VP_026 tsst Recovery
VP_026 ftsst Baseline
VP_026 ftsst Prep
VP_026 ftsst Talk
VP_026 ftsst Math
VP_026 ftsst Recovery
VP_027 tsst Baseline
VP_027 tsst Prep
VP_027 tsst Talk
VP_027 tsst Math
VP_027 tsst Recovery
VP_027 ftsst Baseline
VP_027 ftsst Prep
VP_027 ftsst Talk
VP_027 ftsst Math
VP_027 ftsst Recovery
VP_031 tsst Baseline
VP_031 tsst Prep
VP_031 tsst Talk
VP_031 tsst Math
VP_031 tsst Recovery
VP_031 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_031 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_031 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_031 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_031 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 tsst Baseline
VP_032 tsst Prep
VP_032 tsst Talk
VP_032 tsst Math
VP_032 tsst Recovery
VP_032 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 tsst Baseline
VP_033 tsst Prep
VP_033 tsst Talk
VP_033 tsst Math
VP_033 tsst Recovery
VP_033 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_034 ftsst Baseline
VP_034 ftsst Prep
VP_034 ftsst Talk
VP_034 ftsst Math
VP_034 ftsst Recovery
VP_036 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_036 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_036 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_036 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_037 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_037 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_037 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_037 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_037 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_041 tsst Baseline
VP_041 tsst Prep
VP_041 tsst Talk
VP_041 tsst Math
VP_041 tsst Recovery
VP_044 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_045 tsst Baseline
VP_045 tsst Prep
VP_045 tsst Talk
VP_045 tsst Math
VP_045 tsst Recovery
VP_045 ftsst Baseline
VP_045 ftsst Prep
VP_045 ftsst Talk
VP_045 ftsst Math
VP_045 ftsst Recovery
VP_050 tsst Baseline
VP_050 tsst Prep
VP_050 tsst Talk
VP_050 tsst Math
VP_050 tsst Recovery
VP_051 tsst Baseline
VP_051 tsst Prep
VP_051 tsst Talk
VP_051 tsst Math
VP_051 tsst Recovery
VP_051 ftsst Baseline
VP_051 ftsst Prep
VP_051 ftsst Talk
VP_051 ftsst Math
VP_051 ftsst Recovery
VP_052 tsst Baseline
VP_052 tsst Prep
VP_052 tsst Talk
VP_052 tsst Math
VP_052 tsst Recovery
VP_053 tsst Baseline
VP_053 tsst Prep
VP_053 tsst Talk
VP_053 tsst Math
VP_053 tsst Recovery
VP_059 tsst Baseline
VP_059 tsst Prep
VP_059 tsst Talk
VP_059 tsst Math
VP_059 tsst Recovery
VP_060 tsst Baseline
VP_060 tsst Prep
VP_060 tsst Talk
VP_060 tsst Math
VP_060 tsst Recovery
VP_060 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 tsst Baseline
VP_061 tsst Prep
VP_061 tsst Talk
VP_061 tsst Math
VP_061 tsst Recovery
VP_061 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_065 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_065 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_065 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_065 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_065 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_066 ftsst Baseline
VP_066 ftsst Prep
VP_066 ftsst Talk
VP_066 ftsst Math
VP_066 ftsst Recovery
VP_067 ftsst Baseline
VP_067 ftsst Prep
VP_067 ftsst Talk
VP_067 ftsst Math
VP_067 ftsst Recovery
VP_075 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_075 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_076 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_077 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_078 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_079 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_080 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_081 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_082 ftsst Baseline
VP_082 ftsst Prep
VP_082 ftsst Talk
VP_082 ftsst Math
VP_082 ftsst Recovery
VP_083 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_083 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_083 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_083 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_083 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_083 ftsst Baseline
VP_083 ftsst Prep
VP_083 ftsst Talk
VP_083 ftsst Math
VP_083 ftsst Recovery
VP_084 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_084 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_085 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_086 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_087 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_088 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_089 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_090 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_091 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_092 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_093 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_094 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_095 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_096 tsst Baseline
VP_096 tsst Prep
VP_096 tsst Talk
VP_096 tsst Math
VP_096 tsst Recovery
VP_096 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_096 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_096 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_096 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_096 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_097 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_098 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_099 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_100 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 tsst Baseline
VP_102 tsst Prep
VP_102 tsst Talk
VP_102 tsst Math
VP_102 tsst Recovery
VP_102 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_103 tsst Baseline
VP_103 tsst Prep
VP_103 tsst Talk
VP_103 tsst Math
VP_103 tsst Recovery
VP_103 ftsst Baseline
VP_103 ftsst Prep
VP_103 ftsst Talk
VP_103 ftsst Math
VP_103 ftsst Recovery
VP_104 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_104 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_105 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_106 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_107 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_108 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_110 tsst Baseline
VP_110 tsst Prep
VP_110 tsst Talk
VP_110 tsst Math
VP_110 tsst Recovery
VP_110 ftsst Baseline
VP_110 ftsst Prep
VP_110 ftsst Talk
VP_110 ftsst Math
VP_110 ftsst Recovery

In [12]:
subset.nilspod

Empty DataFrame
Columns: [(157e, gyr_x), (157e, gyr_y), (157e, gyr_z), (157e, acc_x), (157e, acc_y), (157e, acc_z), (3d73, gyr_x), (3d73, gyr_y), (3d73, gyr_z), (3d73, acc_x), (3d73, acc_y), (3d73, acc_z), (9e02, gyr_x), (9e02, gyr_y), (9e02, gyr_z), (9e02, acc_x), (9e02, acc_y), (9e02, acc_z), (9e02, analog_0), (9e02, analog_1), (9e02, analog_2), (b0c2, gyr_x), (b0c2, gyr_y), (b0c2, gyr_z), (b0c2, acc_x), (b0c2, acc_y), (b0c2, acc_z), (b0c2, ecg)]
Index: []

[0 rows x 28 columns]

In [19]:
pd.DataFrame(error_dict, index=["error"]).T.to_csv("nilspod_errors.csv")

In [ ]:
data.plot()

In [20]:
hr_results_all

                                HRV_MeanNN   HRV_SDNN  HRV_SDANN1  HRV_SDNNI1  \
participant condition phase
VP_009      ftsst     Baseline  898.486126  66.827594   28.290076   60.847482
                      Prep      824.761285  86.299038   45.502466   75.850667
                      Talk      618.233945  53.304383   28.729384   44.693985
                      Math      600.116986  64.491980   31.328594   57.394659
                      Recovery  933.919271  75.449654   38.583202   67.011343
...                                    ...        ...         ...         ...
VP_109      ftsst     Baseline  886.972253  78.953451   51.501868   63.596989
                      Prep      864.215106  64.011666   24.833483   60.639128
                      Talk      764.242788  93.110766   52.354985   79.447680
                      Math      858.039374  65.842918   19.654141   63.352820
                      Recovery  919.687500  54.425110   20.454770   51.449747

                                HRV_SDANN2  HRV_SDNNI2  HRV_SDANN5  \
participant condition phase
VP_009      ftsst     Baseline         NaN         NaN         NaN
                      Prep             NaN         NaN         NaN
                      Talk       29.563064   46.702577         NaN
                      Math       34.042728   57.940831         NaN
                      Recovery   39.328888   66.824875         NaN
...                                    ...         ...         ...
VP_109      ftsst     Baseline   31.933327   74.774443         NaN
                      Prep             NaN         NaN         NaN
                      Talk       54.037938   82.350369         NaN
                      Math        4.078767   65.946600         NaN
                      Recovery         NaN         NaN         NaN

                                HRV_SDNNI5  HRV_RMSSD   HRV_SDSD  ...  \
participant condition phase                                       ...
VP_009      ftsst     Baseline         NaN  66.790022  66.927028  ...
                      Prep             NaN  98.185154  98.321993  ...
                      Talk             NaN  29.642852  29.669299  ...
                      Math             NaN  31.813184  31.840641  ...
                      Recovery         NaN  73.081832  73.195221  ...
...                                    ...        ...        ...  ...
VP_109      ftsst     Baseline         NaN  57.983836  58.069745  ...
                      Prep             NaN  61.219055  61.308600  ...
                      Talk             NaN  46.953804  47.005147  ...
                      Math             NaN  53.259690  53.322273  ...
                      Recovery         NaN  62.131952  62.228015  ...

                                HRV_FuzzyEn  HRV_MSEn  HRV_CMSEn  HRV_RCMSEn  \
participant condition phase
VP_009      ftsst     Baseline     1.307057  1.290359   1.354511    2.095387
                      Prep         1.537730  1.343786   1.309379    2.186214
                      Talk         0.948468  1.325866   1.280708    2.085846
                      Math         0.886150  1.559579   1.327715    2.149179
                      Recovery     1.401001  1.190378   1.387812    2.203495
...                                     ...       ...        ...         ...
VP_109      ftsst     Baseline     1.190293  1.488962   1.416344    2.068376
                      Prep         1.419649  1.436367   1.456587    2.170387
                      Talk         0.918443  1.536778   1.336290    2.207200
                      Math         1.275860  1.364689   1.383268    2.118099
                      Recovery     1.463555  1.313366   1.295966    1.963891

                                  HRV_CD   HRV_HFD   HRV_KFD   HRV_LZC  \
participant condition phase
VP_009      ftsst     Baseline  1.746561  1.898754  3.042605  0.886506
                      Prep      1.873705  1.997235  6.946891  0.919951
                      Talk      1.756819  1.755961  2.704593  0.700522
                      Math      1.688683  1.732683  2.957525  0.553156
                      Recovery  1.919939  1.929067  4.652286  0.900910
...                                  ...       ...       ...       ...
VP_109      ftsst     Baseline  1.881192  1.856165  3.842828  0.818200
                      Prep      1.863126  1.873685  4.289656  0.883948
                      Talk      1.771620  1.687977  3.092548  0.698615
                      Math      1.861438  1.785502  4.175701  0.900412
                      Recovery  1.774981  2.008497  5.285704  0.847267

                                   HR_Mean      HR_SD
participant condition phase
VP_009      ftsst     Baseline   67.158945   5.089042
                      Prep       73.564106   7.829233
                      Talk       97.787170   8.406008
                      Math      101.149631  10.975796
                      Recovery   64.678324   5.433539
...                                    ...        ...
VP_109      ftsst     Baseline   68.209942   6.402470
                      Prep       69.815752   5.306773
                      Talk       79.681072   9.717384
                      Math       70.346755   5.516417
                      Recovery   65.475178   4.013297

[740 rows x 83 columns]

In [21]:
hr_results_all.index.names = ["subject", "condition", "phase"]

In [22]:
hr_results_all = hr_results_all.unstack(["condition", "phase"])

In [23]:
# flatten multiindex
hr_results_all.columns = ["_".join(col).strip() for col in hr_results_all.columns.values]

In [24]:
hr_results_all

,HRV_MeanNN_ftsst_Baseline,HRV_MeanNN_ftsst_Prep,HRV_MeanNN_ftsst_Talk,HRV_MeanNN_ftsst_Math,HRV_MeanNN_ftsst_Recovery,HRV_MeanNN_tsst_Baseline,HRV_MeanNN_tsst_Prep,HRV_MeanNN_tsst_Talk,HRV_MeanNN_tsst_Math,HRV_MeanNN_tsst_Recovery,...,HR_SD_ftsst_Baseline,HR_SD_ftsst_Prep,HR_SD_ftsst_Talk,HR_SD_ftsst_Math,HR_SD_ftsst_Recovery,HR_SD_tsst_Baseline,HR_SD_tsst_Prep,HR_SD_tsst_Talk,HR_SD_tsst_Math,HR_SD_tsst_Recovery
subject,,,,,,,,,,,,,,,,,,,,,
VP_009,898.486126,824.761285,618.233945,600.116986,933.919271,NaN,NaN,NaN,NaN,NaN,...,5.089042,7.829233,8.406008,10.975796,5.433539,NaN,NaN,NaN,NaN,NaN
VP_010,819.373292,714.104259,625.696569,663.887175,777.546146,NaN,NaN,NaN,NaN,NaN,...,3.682913,5.296122,7.286303,7.222672,3.864387,NaN,NaN,NaN,NaN,NaN
VP_011,824.154006,885.358364,682.090184,644.070688,900.496517,707.786396,759.093238,611.348977,595.156796,802.681872,...,5.714174,5.383550,7.789262,7.002217,5.470638,5.645469,7.024322,8.996232,7.871257,5.805243
VP_012,814.726027,717.689732,706.927190,665.844167,797.494540,753.984375,755.228062,686.560212,707.337307,776.461039,...,3.000240,5.214479,7.163562,8.267183,2.453322,3.376454,5.031209,7.687287,5.068878,3.230596
VP_013,834.055101,766.289465,688.015464,665.203937,811.300526,828.214031,684.884584,604.052823,576.227492,826.414571,...,7.412168,7.718145,8.015059,9.030232,9.677650,7.363355,7.395074,11.699704,11.684008,5.433792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_105,741.588732,733.664773,696.053890,699.313256,718.358420,741.053427,698.664608,632.692199,616.490931,730.688955,...,5.105657,5.231419,7.438361,7.173384,6.826087,5.930771,5.966947,9.926151,9.599764,4.983377
VP_106,756.457674,682.610887,655.494888,685.583178,747.165290,742.078993,602.950394,570.143581,657.006836,761.510417,...,9.632391,7.265576,7.846745,7.710195,6.501738,11.820724,11.029433,10.582881,11.269684,6.551911
VP_107,785.352078,725.988307,600.037457,606.745177,792.397357,588.005967,594.194424,487.156384,484.230917,702.987132,...,4.564982,5.553720,8.147325,7.877548,4.922817,7.372233,6.414753,8.091317,7.855973,3.986672
VP_108,692.590784,630.336145,626.935402,631.538878,762.735172,712.180398,682.278047,639.317994,526.171875,768.792503,...,3.769122,4.137316,8.003236,7.448097,4.597293,4.762962,5.982588,6.655507,9.383871,4.234084
VP_109,886.972253,864.215106,764.242788,858.039374,919.687500,863.834447,736.760374,652.822532,720.515951,830.224204,...,6.402470,5.306773,9.717384,5.516417,4.013297,5.383651,7.272666,8.294829,6.300583,5.747945

In [25]:
hr_results_all.to_csv("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/ecg/preliminary/nilspod_hr_v_results.csv")